version: "3.3"
x-development-volumes: &development-volumes
  volumes:
    - ./tests:/workspace/app/tests/
    - ./spannermc:/workspace/app/spannermc/
    - ./Makefile:/workspace/app/Makefile
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./poetry.toml:/workspace/app/poetry.toml
    - ./poetry.lock:/workspace/app/poetry.lock
services:
  localmail:
    image: mailhog/mailhog:v1.0.0
    container_name: localmail
    ports:
      - "8025:8025"
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
      args:
        # remove this to build for production.
        POETRY_INSTALL_ARGS: --with=dev
    image: app:latest-dev
    command: litestar run --reload
    restart: always
    <<: *development-volumes
  migrator:
    image: app:latest-dev
    command: litestar database upgrade-database
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
