timeout: "1800s"
steps:
  - id: "Building containers"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "ENV_SECRETS=${_ENV_SECRETS}",
        "-t",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:${BRANCH_NAME}-${SHORT_SHA}",
        "--file",
        "deploy/docker/run/Dockerfile",
        ".",
      ]
  - id: "Tagging image as latest"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:${BRANCH_NAME}-${SHORT_SHA}",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:latest",
      ]
  - id: "Pushing tag for git revision"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:${BRANCH_NAME}-${SHORT_SHA}",
      ]
  - id: "Pushing tag for latest"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:latest",
      ]
  - id: "apply database migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - -c
      - |
        /buildstep/execute.sh \
        -i ${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:${BRANCH_NAME}-${SHORT_SHA} \
        -e PATH=/workspace/app/.venv/bin:$$PATH \
        -e PYTHONPATH=/workspace/app/ \
        -- spannermc database upgrade
  - id: "Deploying to CloudRun"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION_NAME}-docker.pkg.dev/${_PROJECT_ID}/spannermc-artifacts/${_SERVICE_NAME}:${BRANCH_NAME}-${SHORT_SHA}",
        "--region",
        "${_REGION_NAME}",
        "--service-account",
        "${_SERVICE_ACCOUNT}",
        "--timeout",
        "45",
        "--memory",
        "${_MEMORY_SIZE}",
        "--max-instances",
        "${_MAX_INSTANCES}",
        "--cpu",
        "1",
        "--port",
        "8000",
        "--project",
        "${_PROJECT_ID}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--execution-environment",
        "gen2",
      ]
