timeout: "1800s"
steps:
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - -c
      - |
        /buildstep/execute.sh \
        -i ${_CONTAINER_IMAGE} \
        -e PATH=/workspace/app/.venv/bin:$$PATH \
        -e PYTHONPATH=/workspace/app/ \
        -- database upgrade
  - id: "Deploying to CloudRun"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_CONTAINER_IMAGE}",
        "--region",
        "${_REGION}",
        "--service-account",
        "${_SERVICE_ACCOUNT}",
        "--timeout",
        "60",
        "--memory",
        "${_MEMORY_SIZE}",
        "--min-instances",
        "1",
        "--max-instances",
        "${_MAX_INSTANCES}",
        "--cpu",
        "1",
        "--port",
        "8080",
        "--project",
        "${_PROJECT_ID}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--execution-environment",
        "gen2",
        "--no-cpu-throttling",
      ]
